FROM python:3.12-slim


RUN apt-get update && apt-get install -y \
    docker.io \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/dagster/app


COPY pyproject.toml .
RUN pip install --no-cache-dir \
    dagster dagster-webserver pandas duckdb underthesea boto3 \
    dbt-core dbt-duckdb